version: "3"

services:
  web:
    build: docker/web
    labels:
      - traefik.backend=web
      - traefik.enable=true
      - traefik.docker.network=proxy_network
      - traefik.port=80
      - traefik.protocol=http
      - traefik.frontend.entryPoints=http
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.rule=Host:${ROOT_URL}
    networks:
      - proxy_network

networks:
  proxy_network:
    external:
      name: proxy_network
