version: "3"

services:
  nats:
    build: docker/nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
    networks:
      - proxy_network

networks:
  proxy_network:
    external:
      name: proxy_network
