version: "3"

services:
  proxy:
    build: docker/proxy
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/tmp:/etc/traefik/acme
    networks:
      - proxy_network

networks:
  proxy_network:
    external:
      name: proxy_network
