version: "3"

services:
  api:
    build: docker/api
    networks:
      - proxy_network
    expose:
      - 8000
    labels:
      - traefik.backend=api
      - traefik.enable=true
      - traefik.docker.network=proxy_network
      - traefik.port=8000
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.rule=Host:api.${ROOT_URL}
      - traefik.passHostHeader=true

networks:
  proxy_network:
    external:
      name: proxy_network
