version: "3"

services:
  ws:
    build: docker/ws-tcp-relay
    networks:
      #- nats_network
      - proxy_network
    ports:
      - 4223:4223
    labels:
      - traefik.backend=ws
      - traefik.enable=true
      - traefik.docker.network=proxy_network
      - traefik.port=4223
      - traefik.protocol=ws
      - traefik.frontend.entryPoints=ws
      - traefik.frontend.rule=Host:ws.${ROOT_URL}
      - traefik.frontend.passHostHeader=true
    command: ws-tcp-relay -p 4223 nats:4222

networks:
  #nats_network:
  #  external:
  #    name: nats_network

  proxy_network:
    external:
      name: proxy_network
