version: "3"

services:
  ws:
    build: docker/ws-tcp-relay
    networks:
      - proxy_network
    labels:
      - traefik.backend=ws
      - traefik.enable=true
      - traefik.docker.network=proxy_network
      - traefik.port=4223
      - traefik.protocol=ws
      - traefik.frontend.entryPoints=http,https,ws,wss
      - traefik.frontend.rule=Host:socket.${ROOT_URL}
      - traefik.passHostHeader=true
    command: ws-tcp-relay -p 4223 nats:4222

networks:
  proxy_network:
    external:
      name: proxy_network
