################################################################
# Globals
################################################################

defaultEntryPoints = ["http", "ws"]

################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
    address = ":80"
    compress = false

################################################################
# Docker configuration backend
################################################################
[docker]
watch = true
domain = "donovan-tengblad.loc"
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
#swarmmode = true
#endpoint = "tcp://127.0.0.1:2375"
